# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accolade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField(default=False)),
                ('userOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOne_set', to=settings.AUTH_USER_MODEL)),
                ('userTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTwo_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tagstring', models.TextField()),
                ('taghash', models.TextField()),
                ('urgent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tagstring', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25, unique=True)),
                ('lemma', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thingType', models.CharField(choices=[('TEXT', 'Text'), ('PLACE', 'Place'), ('URL', 'Url')], default='TEXT', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceThing',
            fields=[
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='friends_best.Thing')),
                ('placeId', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextThing',
            fields=[
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='friends_best.Thing')),
                ('description', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlThing',
            fields=[
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='friends_best.Thing')),
                ('url', models.TextField(max_length=400, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends_best.Tag'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='tags',
            field=models.ManyToManyField(to='friends_best.Tag'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends_best.Thing'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='tags',
            field=models.ManyToManyField(to='friends_best.Tag'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends_best.Query'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pin',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends_best.Query'),
        ),
        migrations.AddField(
            model_name='pin',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends_best.Thing'),
        ),
        migrations.AddField(
            model_name='accolade',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends_best.Recommendation'),
        ),
        migrations.AddField(
            model_name='accolade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together=set([('user', 'taghash')]),
        ),
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together=set([('thing', 'query')]),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([('userOne', 'userTwo')]),
        ),
        migrations.AlterUniqueTogether(
            name='accolade',
            unique_together=set([('user', 'recommendation')]),
        ),
    ]
