# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_best', '0006_auto_20160406_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='userOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='userTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship2', to=settings.AUTH_USER_MODEL),
        ),
    ]
